### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by SomosAMambo** [BKWLD/decoy#23] opened 2017-03-26 16:59 UTC
**Image related issues:**

1. On duplicating for another locale, images relationships are not duplicated. The checkbox `Include images and files` is checked.
2. On hovering a image field with a `Compare` locale radio checked, the tooltip image is broken.

**Comment by weotch** [comment] 2017-03-27 21:00
As part of fixing this, I'm planning to remove those checkboxes ... The "create" button will always duplicate all copy and assets.  Part of my reasoning for this is because it's simpler and part of it is so that errors don't get thrown if a column that is required gets `NULL`ed out.

@SomosAMambo do you see any issue with removing them?  Like in your use case, do you have a reason that you would want to start from a blank slate?

**Comment by SomosAMambo** [comment] 2017-03-27 23:28
> @SomosAMambo do you see any issue with removing them? Like in your use case, do you have a reason that you would want to start from a blank slate?
Nope. Do it. 

I've noticed another issue when duplicating a model to a new locale. If there is a upload field, the string in that field is duplicated, but the file don't. The problem is, when replacing the duplicated model upload field, the original file is deleted. So, the original model loses it's uploaded files.

**Comment by weotch** [comment] 2017-03-27 23:46
Re:

> I've noticed another issue when duplicating a model to a new locale. If there is a upload field, the string in that field is duplicated, but the file don't. The problem is, when replacing the duplicated model upload field, the original file is deleted. So, the original model loses it's uploaded files.

Check out this addition to the docs: https://github.com/BKWLD/decoy/commit/5b3bfd7655ca292e0eaae5b93c9e256e76ae62df.  I think the problem is that your file field wasn't mentioned in that `upload_attributes` array.

**Comment by weotch** [comment] 2017-03-28 17:20
(2) Should be fixed now, seeing this when using the /example app:

![](http://yo.bkwld.com/3I2p152E0t1e/Image%202017-03-28%20at%2010.20.02%20AM.png)

**Comment by SomosAMambo** [comment] 2017-03-29 20:50
@weotch Robert,

> Check out this addition to the docs: 5b3bfd7. I think the problem is that your upload field wasn't mentioned in that upload_attributes array.

My model has it:
```php
    /**
     * Uploadable attributes
     *
     * @var array
     */
    protected $upload_attributes = ['file'];
```
See my screencap: https://www.dropbox.com/s/u2lue13vski1jqm/screencapdecoy.mov?dl=0

**Comment by weotch** [comment] 2017-03-30 16:13
Your `imagem` field is a `Former::upload()` type of field, right?  

Did you customize anything about how files get stored or is it just the default (storing in `public/uploads/`)?

---

I just tested and I can't reproduce locally ... note, you'll need to `composer update bkwld/cloner` and republish the assets directory (`php artisan vendor:publish --provider="Bkwld\Decoy\ServiceProvider" --tag=assets`)

**Comment by SomosAMambo** [comment] 2017-03-30 19:20
> Your imagem field is a Former::upload() type of field, right?

Yup.

> Did you customize anything about how files get stored or is it just the default (storing in public/uploads/)?

Nope.

Updating cloner... 
Publishing assets...
Testing...
Same result. I'll let cloner explicit in my composer with dev-master branch.
```
Problem 1
    - bkwld/decoy dev-master requires bkwld/cloner ^3.2.2 -> satisfiable by bkwld/cloner[3.2.2] but these conflict with your requirements or minimum-stability.
    - bkwld/decoy dev-master requires bkwld/cloner ^3.2.2 -> satisfiable by bkwld/cloner[3.2.2] but these conflict with your requirements or minimum-stability.
    - Installation request for bkwld/decoy dev-master -> satisfiable by bkwld/decoy[dev-master].
```
Which Decoy tag should we use? Sorry... no time to figure it out...

**Comment by weotch** [comment] 2017-03-30 19:55
I'm referring to `dev-master`.  Try a general `composer upgrade` with that version constraint.

**Comment by SomosAMambo** [comment] 2017-03-31 17:36
We are running `dev-master 8fb5d65`. For us the behavior is the same as in the screencap. :(
Maybe we are scr*wing something up...

**Comment by brokenhd** [comment] 2017-03-31 19:31
I just tested this locally using `dev-master` and our example app and could not reproduce the issue: http://yo.bkwld.com/281F1L1r160k

**Closed by brokenhd** 2017-03-31 19:31 UTC

**Comment by weotch** [comment] 2017-03-31 20:57
We just released [5.3.0](https://github.com/BKWLD/decoy/releases/tag/5.3.0), maybe upgrading to this tagged release will fix it?  Like in case there is still some composer related issue?  Remember to re-publish the assets.

**Comment by SomosAMambo** [comment] 2017-03-31 21:22
Sorry guys... 

When I upgraded to the `dev-master 8fb5d65`, I forgot to republish the assets... Just did and retested... it's working like a charm. Thank you! You are great!

![Shame!](https://media.giphy.com/media/gyYJYyCPezUWI/giphy.gif)

**Comment by weotch** [comment] 2017-03-31 21:23
Hahaha, all good.  Glad it works!
