### ISSUE TITLE
FatalErrorException on first login

### ISSUE THREAD

**Issue by symfonycoda** [BKWLD/decoy#35] opened 2017-04-16 10:02 UTC
Hi

I have followed your quick-start instructions (http://docs.decoy.bukwild.com/quick-start), and everything seems to work until I go to /admin in the browser. The error comes up as follows:

Symfony\Component\Debug\Exception\FatalErrorException in d6b3bed5a9cf6ab689b4081dcf6401412aed3c3f.php line 0:
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: scandir(/home/vagrant/Code/Sites/thebackend/app/Console/Commands): failed to open dir: No such file or directory (View: /home/vagrant/Code/Sites/thebackend/vendor/bkwld/decoy/views/layouts/sidebar/_nav.haml) (View: /home/vagrant/Code/Sites/thebackend/vendor/bkwld/decoy/views/layouts/sidebar/_nav.haml)

The admin user has been set up in the database, and it seems to log me in, but the re-direct then throws the error.

My environment is Homestead 
Thanks

@symfonycoda
@UKLaravel

**Comment by eminos** [comment] 2017-04-16 10:20
Duplicate of #33 . Just create the **Commands** directory.
But this should really be fixed in Decoy imo...

**Comment by symfonycoda** [comment] 2017-04-16 10:26
Many thanks. yes that works. 

...if not fixed, then at least added to the documentation?

**Comment by weotch** [comment] 2017-04-17 16:12
@brokenhd can you add Commands to the tests and then fix this fatal error so we're not expecting that directory to exist? 

On a test of running a command, let's test the laravel cache:clear one.

**Closed** 2017-04-21 20:36 UTC
